default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: database_development
  host: ls-770bc7ef37e0dd90b4be5bacafd8c7cb19b4125f.c5yssiuzporz.us-east-1.rds.amazonaws.com
  port: 3306
  username: dbmasteruser
  password: 4NN>.9F;sB]cT+)m0:2p1&fZbl4?9)s*
