default: &default
  adapter: mysql2
  encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: database_development
  username: root
  password: test

production:
  <<: *default
  database:
  username:
  password:

test:
  <<: *default
  database: database_test
  username: root
  password: test
